import { writable } from 'svelte/store';

const STORAGE_KEY = 'docshelf_docs';

function loadDocs() {
  if (typeof localStorage === 'undefined') return getSamples();
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : getSamples();
  } catch { return getSamples(); }
}

function getSamples() {
  return [
    {
      id: '1', title: 'Introduction to Distributed Systems', author: 'M. van Steen',
      category: 'technical', description: 'Comprehensive overview of distributed computing, consistency models, and fault tolerance.',
      size: '4.2 MB', pages: 318, date: '2024-11-15',
      tags: ['networking', 'systems'], fileName: 'distributed-systems.pdf', fileData: null
    },
    {
      id: '2', title: 'The Mutus Liber', author: 'Anonymous (1677)',
      category: 'books', description: 'The silent book — alchemical emblems without words. A visual treatise on the Great Work.',
      size: '18.7 MB', pages: 21, date: '2024-10-03',
      tags: ['alchemy', 'hermetic', 'esoteric'], fileName: 'mutus-liber.pdf', fileData: null
    },
    {
      id: '3', title: 'NixOS Manual', author: 'NixOS Contributors',
      category: 'technical', description: 'Official reference for NixOS. Configuration, modules, package management, deployment.',
      size: '2.1 MB', pages: 489, date: '2025-01-20',
      tags: ['nixos', 'linux'], fileName: 'nixos-manual.pdf', fileData: null
    }
  ];
}

function createDocsStore() {
  const { subscribe, set, update } = writable(loadDocs());
  const save = (docs) => {
    if (typeof localStorage !== 'undefined')
      localStorage.setItem(STORAGE_KEY, JSON.stringify(docs));
  };
  return {
    subscribe,
    add: (doc) => update(docs => { const next = [doc, ...docs]; save(next); return next; }),
    remove: (id) => update(docs => { const next = docs.filter(d => d.id !== id); save(next); return next; }),
  };
}

export const docs = createDocsStore();
export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'technical', label: 'Technical' },
  { id: 'books', label: 'Books' },
  { id: 'research', label: 'Research' },
  { id: 'other', label: 'Other' }
];

export const goals = [
{ id: '1', title: 'No intermediary means no one between Me and God', color: '#b8860b', gradient: 'linear-gradient(135deg, #0f7a5a 0%, #c8a000 45%, #ffd700 70%, #986e24 100%)', textColor: '#fff8dc', summary: 'Direct connection between people, without brokers or middlemen.', description: 'Every soul has the right to act, speak, and transact without a gatekeeper standing between them and the world. No intermediary means no toll, no permission, no delay imposed by those who profit from the middle. When two people meet in honest exchange, no third party should extract value from that meeting. This goal calls for the removal of unnecessary layers — in finance, in communication, in governance — so that the living may deal with one another directly, freely, and with full accountability to each other alone.', docs: [] },  
{ id: '2', title: 'Tally is the new word to exchange without debt, start measure without masters', color: '#b85c00', gradient: 'linear-gradient(135deg, #7a2e00 0%, #c96a00 60%, #f0a040 100%)', textColor: '#fde8c0', summary: 'Every exchange seen by all. Nothing hidden.', description: 'A tally is the oldest form of honest record — a mark made in the open, witnessed by all, altered by none. The Tally goal affirms that accounts of value, exchange, debt, and contribution must be legible to every participant. Hidden books breed hidden power. When the record is open, those who hold it cannot lie about what it contains. This goal covers transparent ledgers, open accounting, public records of collective decisions, and the right of every member of a community to read the record that concerns them.', docs: [] },
  { id: '3', title: 'No permission need to build your own house', color: '#1a3a8a', gradient: 'linear-gradient(135deg, #0d1f5c 0%, #1a3a8a 50%, #3a6ae8 100%)', textColor: '#c0d8ff', summary: 'The right to build shelter and infrastructure without prohibition.', description: 'To build is one of the most fundamental acts of a living being. A home, a workshop, a barn, a path — these are extensions of the body into the world. Build Free affirms that no person or institution may prohibit the construction of shelter, tools, or infrastructure needed for dignified life. Codes, permits, and restrictions that exist to extract fees or enforce dependency rather than protect genuine safety are illegitimate. Every soul has the right to shape their dwelling and their land according to their needs, their knowledge, and their community\'s agreement.', docs: [] },
  { id: '4', title: 'Engines that work on any local fuel, run clean — the knowledge that was buried', color: '#8a1a1a', gradient: 'linear-gradient(135deg, #5c0a0a 0%, #a02020 50%, #e04040 100%)', textColor: '#ffd0d0', summary: 'Energy and productive power freely available to all communities.', description: 'The engine of life is energy — the capacity to do work, to move, to transform. When energy is monopolised, everything downstream is controlled. Living Engine affirms that communities must have access to the means of generating, storing, and distributing power: mechanical, electrical, thermal, and biological. This includes the right to build mills, collect water, harness wind, ferment fuel, and maintain engines without dependency on centralised suppliers. A community that controls its own energy controls its own future.', docs: [] },
  { id: '5', title: 'Electroculture and permaculture — recovering suppressed agricultural knowledge', color: '#2d6010', gradient: 'linear-gradient(135deg, #1a3a08 0%, #2d6010 50%, #4a9a18 100%)', textColor: '#c8f080', summary: 'Soil health as the foundation of all living systems.', description: 'Soil is not dirt. It is a living system of incomprehensible complexity — billions of organisms per handful, cycling nutrients, holding water, growing food, sequestering carbon, and anchoring ecosystems. Living Soil affirms that the care, regeneration, and protection of topsoil is a primary obligation of any community that intends to persist. This goal covers composting, biological farming, aquaponics, forest gardening, and all practices that build rather than deplete the living layer beneath our feet. Dead soil means dead community.', docs: [] },
  { id: '6', title: 'Pure food, grown clean, shared openly', color: '#8a4a00', gradient: 'linear-gradient(135deg, #5c2800 0%, #8a4a00 50%, #c87820 100%)', textColor: '#ffd8a0', summary: 'Honest food, honestly grown, shared without adulteration.', description: 'The table is where life sustains itself. What is placed on it — and how it was grown, prepared, and shared — defines the health and integrity of a community. The Clean Table affirms the right to food that is free of hidden adulterants, grown without toxic inputs, and exchanged without deception about its nature or origin. It covers the right to grow, slaughter, ferment, preserve, and share food without bureaucratic prohibition. It also affirms the sacred character of the shared meal as a bond between people.', docs: [] },
  { id: '7', title: 'Water flows free — a living commons for all', color: '#0a6080', gradient: 'linear-gradient(135deg, #053a52 0%, #0a6080 50%, #10a8d8 100%)', textColor: '#a0e8ff', summary: 'Water as a commons — protected, clean, and freely accessible.', description: 'Water is not a commodity. It is the precondition of all life and cannot be owned in the way that objects are owned. Sacred Water affirms that access to clean water — for drinking, bathing, irrigation, and aquatic life — is a right that no entity may extinguish through purchase, enclosure, or pollution. Communities have both the right and the obligation to protect their water sources, manage them as commons, and refuse the privatisation of rivers, aquifers, and rainfall. Water belongs to the living.', docs: [] },
  { id: '8', title: 'Open skies, clean air — a birthright of every living soul', color: '#0a4a7a', gradient: 'linear-gradient(135deg, #051e3e 0%, #0a4a7a 50%, #1878c8 100%)', textColor: '#b0d8ff', summary: 'Clean air and open skies as a birthright of all living beings.', description: 'Air cannot be enclosed, but it can be poisoned, and the sky above cannot be owned, but it can be denied. Blue Sky affirms that the atmosphere is a shared commons that no entity may degrade through emissions, spray, or occupation without consent of those who breathe beneath it. This goal covers air quality, the right to unobstructed sky, freedom from electromagnetic saturation without consent, and the protection of atmospheric conditions that sustain biological life. What enters the air enters every lung.', docs: [] },
  { id: '9', title: 'Full sovereignty over your own living body', color: '#5a1a7a', gradient: 'linear-gradient(135deg, #32085a 0%, #5a1a7a 50%, #9030c0 100%)', textColor: '#e8c0ff', summary: 'Sovereignty over one\'s own body, health, and medical choices.', description: 'No authority — governmental, medical, or religious — may claim jurisdiction over the body of a living soul without that soul\'s full, informed, and freely given consent. The Living Body affirms the absolute sovereignty of each person over their own flesh: what enters it, what is done to it, how it is treated in illness, and how it is cared for in death. This goal covers medical autonomy, the right to choose or refuse treatment, access to traditional and herbal medicine, bodily integrity, and freedom from forced intervention of any kind.', docs: [] },
  { id: '10', title: 'All knowledge freed, preserved and open to every soul', color: '#0f5a38', gradient: 'linear-gradient(135deg, #083020 0%, #0f5a38 50%, #18a060 100%)', textColor: '#a0f0c8', summary: 'Knowledge freely preserved, shared, and accessible to all.', description: 'Knowledge that is locked away serves only its keeper. Open Archive affirms that the accumulated learning of humanity — its books, its techniques, its maps, its histories, its sciences, its arts — belongs to everyone and must be preserved, copied, and distributed without restriction. This goal covers open libraries, free educational materials, the digitisation and sharing of rare texts, oral tradition preservation, and the right to learn without paying tribute to gatekeepers of knowledge. This archive is one expression of that goal.', docs: [] },
  { id: '11', title: 'Living wisdom passed hand to hand, elder to youth', color: '#7a5200', gradient: 'linear-gradient(135deg, #4a2e00 0%, #7a5200 50%, #c08010 100%)', textColor: '#ffe0a0', summary: 'Education rooted in living knowledge, passed directly between people.', description: 'True teaching is not the transfer of certified information from an accredited institution. It is the living transmission of understanding from one person to another — from elder to youth, from craftsperson to apprentice, from farmer to child. Living Teaching affirms the right to educate and be educated outside of institutional systems, to homeschool, to learn through doing, and to pass on knowledge through direct relationship. Credentials that gate-keep rather than verify are obstacles to living teaching, not expressions of it.', docs: [] },
  { id: '12', title: 'Every soul stands on enough land to grow and build', color: '#4a3000', gradient: 'linear-gradient(135deg, #2a1500 0%, #4a3000 50%, #8a5818 100%)', textColor: '#f0c878', summary: 'Access to land as a foundation for dignified, self-sufficient life.', description: 'Land is not created by its claimants. It exists before any title, any fence, any deed. Free Land affirms that every person and every community must have access to enough land to grow food, build shelter, and sustain life. This does not mean that all land claims are illegitimate, but that no system of land ownership may leave the majority landless while a minority holds vast territories idle or extractive. Communities have the right to occupy, cultivate, and steward land that sustains them, regardless of paper claims made by distant entities.', docs: [] },
  { id: '13', title: 'Stop delegating. Gather, decide together', color: '#0f5858', gradient: 'linear-gradient(135deg, #083030 0%, #0f5858 50%, #18a0a0 100%)', textColor: '#a0f0f0', summary: 'Governance by council, consensus, and direct participation.', description: 'The circle is the oldest form of governance — everyone visible to everyone else, no head of table, no hidden deliberation. The Circle affirms that decisions affecting a community must be made by that community, in open assembly, with every voice having equal standing. This is not the representative democracy of elected strangers, but the direct governance of those who live with the consequences of each decision. The circle meets, it listens, it deliberates, and it reaches resolution through genuine agreement rather than majority domination.', docs: [] },
  { id: '14', title: 'Locating living traditions that never broke, bringing the knowledge back', color: '#5a3000', gradient: 'linear-gradient(135deg, #301800 0%, #5a3000 50%, #a05810 100%)', textColor: '#f0c880', summary: 'Honouring the bond between generations and the wisdom of elders.', description: 'A community without elders has no memory. A community that discards its elders loses the accumulated wisdom of lifetimes. Elder Bond affirms the obligation of each generation to honour, care for, and learn from those who came before — and the obligation of elders to transmit what they know with honesty and generosity. This goal covers intergenerational living, the role of elders in councils, the preservation of traditional knowledge, and the rejection of cultures that discard the old in favour of the merely new.', docs: [] },
  { id: '15', title: 'Documenting what works, sharing it freely. Letting the living way speak for itself', color: '#1a1a6a', gradient: 'linear-gradient(135deg, #0a0a3a 0%, #1a1a6a 50%, #3030b8 100%)', textColor: '#c0c0ff', summary: 'The living way growing through example, invitation, and free sharing.', description: 'No living way spreads by force. It spreads because those who live it demonstrate that it works — that it produces flourishing, dignity, and genuine freedom. The Way Spreads affirms that the expansion of these principles must happen through example, open invitation, and the free sharing of knowledge, tools, and experience. Communities that embody these goals become beacons. They do not conquer or convert — they demonstrate. Those who see and recognise the truth of what they see are welcome to join, to learn, and to begin their own expression of the living way.', docs: [] },
  { id: '16', title: 'Measuring soil, sky, water and the living condition of every solven. Nothing else', color: '#4a4a00', gradient: 'linear-gradient(135deg, #282800 0%, #4a4a00 50%, #888800 100%)', textColor: '#e8e890', summary: 'Measuring success by what genuinely thrives — life, beauty, and abundance.', description: 'The final measure of any community is not its GDP, its military strength, or its compliance with external standards. It is what actually flourishes within it — the health of its children, the vitality of its soil, the richness of its culture, the depth of its relationships, the beauty of what it makes, and the freedom of those who live there. What Flourishes affirms that all goals of the living way must be evaluated by this single standard: does life thrive here? If yes, the way is working. If not, something must change.', docs: [] },
];